# https://docs.github.com/en/actions/guides/creating-postgresql-service-containers
name: python_tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  python_tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
    runs-on: ubuntu-latest
    services:
      # Label does not set the Postgres host name which will be localhost
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: runner
          POSTGRES_HOST_AUTH_METHOD: trust
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Map TCP port 5432 on service container to the host
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v2
        with:
          path: ~/infogami_python_venv
          key: ${{ runner.os }}-venv-${{ hashFiles('requirements*.txt') }}
      - run: python3 -m venv ~/infogami_python_venv
      - name: Install dependencies
        run: |
          source ~/infogami_python_venv/bin/activate
          pip install -r requirements_test.txt
      - name: Run tests
        run: |
          source ~/infogami_python_venv/bin/activate
          scripts/run_python_linters.sh
          scripts/run_python_tests.sh
          scripts/run_doctests.sh
