# https://docs.github.com/en/actions/guides/creating-postgresql-service-containers
name: python_tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  python_tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
    runs-on: ubuntu-latest
    services:
      # Label does not set the Postgres host name which will be localhost
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: runner
          POSTGRES_HOST_AUTH_METHOD: trust
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Map TCP port 5432 on service container to the host
          - 5432:5432
    steps:
      - if: "contains(matrix.python-version, '-dev')"
        run: sudo apt-get install -y libxml2 libxslt-dev
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v4
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-venv-${{ env.pythonLocation }}-${{ hashFiles('requirements*.txt') }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements_test.txt
      - run: scripts/run_python_linters.sh
      - run: scripts/run_python_tests.sh
      - run: scripts/run_doctests.sh
